export default {
  name: "graphql-editor-backend",
  version: "0.0.0",
  description: "Automatically generated by graphql-editor",
  main: "lib/index.js",
  scripts: {
    build: "tsc",
  },
  devDependencies: {
    "@types/node": "^12.6.9",
    "@types/node-fetch": "^2.5.7",
    typescript: "latest",
  },
  dependencies: {
    "node-fetch": "^2.6.0",
  },
};
