export default {
  name: "graphql-editor-backend",
  version: "0.0.0",
  description: "Automatically generated by graphql-editor",
  main: "lib/index.js",
  scripts: {
    build: "tsc",
  },
  devDependencies: {
    "@types/node": "^16.11.7",
    typescript: "latest",
  },
  dependencies: {
    "stucco-js": "latest",
  },
};
