export default {
  name: "graphql-editor-backend",
  version: "0.0.0",
  description: "Automatically generated by graphql-editor",
  main: "lib/index.js",
  scripts: {
    build: "tsc",
  },
  devDependencies: {
    "@types/jsonwebtoken": "^8.5.6",
    "@types/node": "^12.6.9",
    "@types/node-fetch": "^2.5.7",
    typescript: "latest",
  },
  dependencies: {
    jsonwebtoken: "^8.5.1",
    mongodb: "^4.2.0",
    "node-fetch": "^2.6.0",
    "stucco-js": "0.9.7",
  },
};
